# Generated by Django 4.1 on 2022-08-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('Alimentação', 'Alimentação'), ('Saúde', 'Saúde'), ('Moradia', 'Moradia'), ('Transporte', 'Transporte'), ('Educação', 'Educação'), ('Lazer', 'Lazer'), ('Imprevistos', 'Imprevistos'), ('Outras', 'Outras')], default='Outras', max_length=15),
        ),
    ]
