# Generated by Django 4.1 on 2022-08-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumo',
            name='despesas',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='resumo',
            name='receitas',
            field=models.FloatField(),
        ),
    ]
