# Generated by Django 4.1 on 2022-08-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_resumomensal_delete_resumo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResumoMensal',
            new_name='Resumo',
        ),
    ]
