# Generated by Django 4.1 on 2022-08-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_resumomensal_resumo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resumo',
            new_name='ResumoMensal',
        ),
    ]
