# Generated by Django 4.1 on 2022-08-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_summary_delete_resumomensal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Summary',
            new_name='Resumo',
        ),
    ]
