# Generated by Django 4.1 on 2022-08-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_summary_despesas_alter_summary_receitas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receita_total', models.FloatField()),
                ('despesa_total', models.FloatField()),
                ('saldo', models.FloatField()),
                ('gasto_categoria', models.FloatField()),
                ('teste', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
