# Generated by Django 4.1 on 2022-08-08 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_monthlysummary_delete_summary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthlySummary',
            new_name='Resumo',
        ),
    ]
