# Generated by Django 4.1 on 2022-08-13 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_resumo_gasto_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resumo',
        ),
    ]
