# Generated by Django 4.1 on 2022-08-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_despesa_usuario_receita_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='usuario',
        ),
    ]
