# Generated by Django 4.1 on 2022-08-16 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_despesa_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='usuario',
        ),
    ]
